-- ---------------------------------------------------------------------------
-- M10 — Notification Management (ADR-018).
--
-- In-app notifications over frozen M1–M9. Two additive tables + two enums:
--   • Notification          — one immutable event record (type, priority, title,
--                             body, actionUrl deep link). No updatedAt — the event
--                             never changes; schoolId loose (ADR-008).
--   • NotificationRecipient — one user's copy: read tracking (isRead/readAt) and the
--                             reversible soft delete (isArchived/archivedAt). Recipients
--                             are resolved once at emit and stored EXPLICITLY (no dynamic
--                             recipient query at read time). @@unique(notificationId,
--                             userId) = one copy per user per event (idempotency floor).
--
-- Notifications are generated by an emit* orchestrator AFTER a publish transaction
-- commits (never before); the wrap lives in transport (routers), the frozen publish
-- SERVICES are untouched (ADR-018 §3). Both FKs RESTRICT (no cascade). RLS is a
-- separate migration (notification_rls, Step 3).
--
-- Purely additive: creates 2 enums + 2 tables + their indexes + their own FKs. NO
-- frozen table (User) is altered — the `User.notifications` back-relation is virtual
-- (no SQL); proven by `prisma migrate diff` (M9 head → schema shows only these CREATEs,
-- zero ALTER).
-- ---------------------------------------------------------------------------

-- CreateEnum
CREATE TYPE "NotificationType" AS ENUM ('HOMEWORK', 'HOMEWORK_PUBLISHED', 'EXAM_PUBLISHED', 'REPORT_CARD_PUBLISHED', 'TIMETABLE_UPDATED', 'STUDY_MATERIAL', 'ANNOUNCEMENT', 'SYSTEM');

-- CreateEnum
CREATE TYPE "NotificationPriority" AS ENUM ('LOW', 'NORMAL', 'HIGH', 'URGENT');

-- CreateTable
CREATE TABLE "Notification" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "type" "NotificationType" NOT NULL,
    "priority" "NotificationPriority" NOT NULL DEFAULT 'NORMAL',
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "actionUrl" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Notification_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "NotificationRecipient" (
    "id" TEXT NOT NULL,
    "notificationId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "isRead" BOOLEAN NOT NULL DEFAULT false,
    "readAt" TIMESTAMP(3),
    "isArchived" BOOLEAN NOT NULL DEFAULT false,
    "archivedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "NotificationRecipient_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Notification_createdAt_idx" ON "Notification"("createdAt");

-- CreateIndex
CREATE INDEX "Notification_schoolId_idx" ON "Notification"("schoolId");

-- CreateIndex  — unread list + badge (hot path)
CREATE INDEX "NotificationRecipient_userId_isRead_createdAt_idx" ON "NotificationRecipient"("userId", "isRead", "createdAt");

-- CreateIndex
CREATE INDEX "NotificationRecipient_notificationId_idx" ON "NotificationRecipient"("notificationId");

-- CreateIndex  — one copy per user per event (idempotency floor)
CREATE UNIQUE INDEX "NotificationRecipient_notificationId_userId_key" ON "NotificationRecipient"("notificationId", "userId");

-- AddForeignKey
ALTER TABLE "NotificationRecipient" ADD CONSTRAINT "NotificationRecipient_notificationId_fkey" FOREIGN KEY ("notificationId") REFERENCES "Notification"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NotificationRecipient" ADD CONSTRAINT "NotificationRecipient_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
